# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productTileGrid
name: Product Tile Grid
icon: display-grid
parameters:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
categoryId: 4e552690-edb9-47a0-8a71-d5752a28365b
previewImageUrl: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1699752392/dsuo4vdwfypaaqcb5eib.png
useTeamPermissions: true
slots:
  - id: tiles
    name: Tiles
    allowedComponents:
      - $test
      - $loop
      - $personalization
      - $p:acbdae81-250a-4db6-a057-3f15fb612d74
      - gridTileImage
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: true
titleParameter: title
canBeComposition: false
created: '2023-11-19T19:47:57.898125+00:00'
updated: '2023-11-19T19:55:53.066209+00:00'
variants:
  - id: carousel
    name: Carousel
