# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productDescription
name: Product Description
icon: shopping-cart
parameters:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig:
      multiline: true
      linesCount: 10
  - id: price
    name: Price
    type: number
    helpText: ''
    typeConfig:
      decimal: true
  - id: currency
    name: Currency
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: USD
          value: USD
        - text: EUR
          value: EUR
      required: true
  - id: availableForSale
    name: Available for Sale
    type: checkbox
    helpText: ''
    typeConfig: null
  - id: options
    name: Options
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - productOption
        - $loop
  - id: variants
    name: Variants
    type: $block
    helpText: ''
    typeConfig:
      allowedTypes:
        - productVariant
        - $loop
categoryId: 4e552690-edb9-47a0-8a71-d5752a28365b
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2023-11-18T22:21:30.658438+00:00'
updated: '2023-11-18T22:40:44.01219+00:00'
