id: product
displayName: Product
ttl: 30
path: /api/products/get-by-ids
custom:
  proposedName: Product
  selectedCategoryIds:
    - '23'
    - '24'
    - '27'
  selectedDisplayField: name
method: GET
purgeKey: 9683e813-2356-4799-9dd0-63f7a2f1ad1c
archetype: singleProduct
variables:
  page:
    type: text
    default: '1'
    displayName: Page
  limit:
    type: text
    default: ''
    displayName: Limit
  keyword:
    type: text
    default: ''
    displayName: Keyword
  sortField:
    type: text
    default: ''
    displayName: Sort Field
  categoryId:
    type: text
    default: ''
    displayName: Category Id
  productIds:
    type: text
    default: ''
    helpText: Array of product ids
    displayName: Product Ids
  sortDirection:
    type: text
    default: ''
    displayName: Sort Direction
parameters:
  - key: id
    value: ${productIds}
  - key: categoryId
    value: ${categoryId}
  - key: keyword
    value: ${keyword}
  - key: sortField
    value: ${sortField}
  - key: sortDirection
    value: ${sortDirection}
  - key: limit
    value: ${limit}
  - key: page
    value: ${page}
dataSourceId: fakeCommerce
allowedOnComponents: []
